### author_name, student_no = 'Amir Afsari', 96105575
### student_no = 'Hamed Khanaki', 96105712

from scanner import Scanner 
from parser import Parser

parse_table = {
            '$': {'Program': ['Statements'], 'Statements': ['Epsilon']},
            ';': {'Statements': ['Epsilon'], 'Statement': ['synch'],
                  'Simple_stmt': ['synch'], 'Compound_stmt': ['synch'],
                  'Assignment_Call': ['synch'], 'B': ['synch'], 'C': ['synch'],
                  'Return_stmt': ['synch'], 'Global_stmt': ['synch'], 'Function_def': ['synch'],
                  'If_stmt': ['synch'], 'Iteration_stmt': ['synch'], 'Expression': ['synch'],
                  'Term': ['synch'], 'Factor': ['synch'], 'Atom': ['synch'],
                  'Return_Value': ['Epsilon'],
                  'Else_block': ['Epsilon'], 'Expression_Prime': ['Epsilon'],
                  'Term_Prime': ['Epsilon'], 'Power': ['Primary'], 'Primary': ['Epsilon']},
            'break': {'Program': ['Statements'], 'Statements': ['Statement', ';', 'Statements'],
                      'Statement': ['Simple_stmt'], 'Simple_stmt': ['break']},
            'continue': {'Program': ['Statements'], 'Statements': ['Statement', ';', 'Statements'],
                         'Statement': ['Simple_stmt'], 'Simple_stmt': ['continue']},
            'ID': {'Program': ['Statements'], 'Statements': ['Statement', ';', 'Statements'],
                   'Statement': ['Simple_stmt'], 'Simple_stmt': ['Assignment_Call'],
                   'Assignment_Call': ['ID', 'B'], 'C': ['Expression'], 'Return_Value': ['Expression'],
                   'Params': ['ID', 'Params_Prime'], 'Relational_Expression': ['Expression', 'Relop', 'Expression'],
                   'Relop': ['synch'], 'Expression': ['Term', 'Expression_Prime'], 'Term': ['Factor', 'Term_Prime'],
                   'Factor': ['Atom', 'Power'], 'Arguments': ['Expression', 'Arguments_Prime'], 'Atom': ['ID']},
            '=': {'B': ['=', 'C']},
            '[': {'B': ['[', 'Expression', ']', '=', 'C'], 'C': ['[', 'Expression', 'List_Rest', ']'],
                  'Power': ['Primary'], 'Primary': ['[', 'Expression', ']', 'Primary'], 'Atom': ['synch']},
            ']': {'List_Rest': ['Epsilon'], 'Expression': ['synch'], 'Term': ['synch'],
                  'Expression_Prime': ['Epsilon'], 'Term_Prime': ['Epsilon'], 'Factor': ['synch'],
                  'Power': ['Primary'], 'Primary': ['Epsilon'], 'Atom': ['synch']},
            '(': {'B': ['(', 'Arguments', ')'], 'Power': ['Primary'], 'Primary': ['(', 'Arguments', ')', 'Primary'],
                  'Atom': ['synch']},
            ')': {'Params': ['Epsilon'], 'Params_Prime': ['Epsilon'], 'Expression': ['synch'], 
                  'Expression_Prime': ['Epsilon'], 'Term': ['synch'], 'Relational_Expression': ['synch'],
                  'Term_Prime': ['Epsilon'], 'Power': ['Primary'], 'Primary': ['Epsilon'], 'Arguments': ['Epsilon'],
                  'Factor': ['synch'], 'Arguments': ['synch'], 'Arguments_Prime': ['Epsilon'], 'Atom': ['synch']},
            ',': {'List_Rest': [',', 'Expression', 'List_Rest'], 'Params_Prime': [',', 'ID', 'Params_Prime'],
                  'Expression': ['synch'], 'Term': ['synch'], 'Factor': ['synch'], 'Atom': ['synch'],
                  'Expression_Prime': ['Epsilon'], 'Term_Prime': ['Epsilon'], 'Power': ['Primary'],
                  'Primary': ['Epsilon'], 'Arguments_Prime': [',', 'Expression', 'Arguments_Prime']},
            'return': {'Program': ['Statements'], 'Statements': ['Statement', ';', 'Statements'],
                       'Statement': ['Simple_stmt'], 'Simple_stmt': ['Return_stmt'],
                       'Return_stmt': ['return', 'Return_Value']},
            'global': {'Program': ['Statements'], 'Statements': ['Statement', ';', 'Statements'],
                       'Statement': ['Simple_stmt'], 'Simple_stmt': ['Global_stmt'], 'Global_stmt': ['global', 'ID']},
            'def': {'Program': ['Statements'], 'Statements': ['Statement', ';', 'Statements'],
                    'Statement': ['Compound_stmt'], 'Compound_stmt': ['Function_def'],
                    'Function_def': ['def', 'ID', '(', 'Params', ')', ':', 'Statements']},
            ':': {'Expression_Prime': ['Epsilon'], 'Term_Prime': ['Epsilon'], 'Power': ['Primary'],
                  'Primary': ['Epsilon'], 'Expression': ['synch'], 'Term': ['synch'], 'Factor': ['synch'],
                  'Atom': ['synch']},
            'if': {'Program': ['Statements'], 'Statements': ['Statement', ';', 'Statements'],
                   'Statement': ['Compound_stmt'], 'Compound_stmt': ['If_stmt'],
                   'If_stmt': ['if', 'Relational_Expression', ':', 'Statements', 'Else_block']},
            'else': {'Statements': ['Epsilon'], 'Else_block': ['else', ':', 'Statements']},
            'while': {'Program': ['Statements'], 'Statements': ['Statement', ';', 'Statements'],
                      'Statement': ['Compound_stmt'], 'Compound_stmt': ['Iteration_stmt'],
                      'Iteration_stmt': ['while', '(', 'Relational_Expression', ')', 'Statements']},
            '==': {'Relop': ['=='], 'Expression': ['synch'], 'Expression_Prime': ['Epsilon'],
                   'Term_Prime': ['Epsilon'], 'Term': ['synch'], 'Factor': ['synch'],
                   'Power': ['Primary'], 'Primary': ['Epsilon'], 'Atom': ['synch']},
            '<': {'Relop': ['<'], 'Expression': ['synch'], 'Expression_Prime': ['Epsilon'],
                  'Term_Prime': ['Epsilon'], 'Term': ['synch'], 'Factor': ['synch'], 'Atom': ['synch'],
                  'Power': ['Primary'], 'Primary': ['Epsilon']},
            '+': {'Expression_Prime': ['+', 'Term', 'Expression_Prime'], 'Term_Prime': ['Epsilon'],
                  'Power': ['Primary'], 'Primary': ['Epsilon'], 'Term': ['synch'], 'Factor': ['synch'],
                  'Atom': ['synch']},
            '-': {'Expression_Prime': ['-', 'Term', 'Expression_Prime'], 'Term_Prime': ['Epsilon'],
                  'Power': ['Primary'], 'Primary': ['Epsilon'], 'Term': ['synch'], 'Factor': ['synch'],
                  'Atom': ['synch']},
            '*': {'Term_Prime': ['*', 'Factor', 'Term_Prime'], 'Power': ['Primary'], 'Primary': ['Epsilon'],
                  'Factor': ['synch'], 'Atom': ['synch']},
            '**': {'Power': ['**', 'Factor'], 'Atom': ['synch']},
            'NUM': {'C': ['Expression'], 'Return_Value': ['Expression'],
                    'Relational_Expression': ['Expression', 'Relop', 'Expression'],
                    'Relop': ['synch'],
                    'Expression': ['Term', 'Expression_Prime'],
                    'Term': ['Factor', 'Term_Prime'], 'Factor': ['Atom', 'Power'],
                    'Arguments': ['Expression', 'Arguments_Prime'], 'Atom': ['NUM']}
        }


scanner = Scanner("input.txt")
parser = Parser(scanner, parse_table)

parser.parse()
